"""empty message

Revision ID: cc07b2be5314
Revises: 
Create Date: 2024-03-17 07:08:31.451004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc07b2be5314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmt_users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password', sa.String(), nullable=True),
    sa.Column('category', postgresql.ENUM('admin', 'driver', name='user_category'), nullable=True),
    sa.Column('is_currently_login', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hmt_users', 'email', nullable=True, unique=False)
    op.drop_table('hmt_users')
    op.execute("""
        DROP TYPE IF EXISTS user_category;
    """)

    # ### end Alembic commands ###
