"""empty message

Revision ID: df10afe3d6ca
Revises: 
Create Date: 2024-03-16 13:10:10.959039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df10afe3d6ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmt_users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('ADMIN', 'DRIVER', name='category'), nullable=True),
    sa.Column('is_currently_login', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hmt_users')
    # ### end Alembic commands ###
